### ISSUE TITLE
Missing documentation for wrapped SDK version

### ISSUE THREAD

**Issue by cosminstirbu** [usabilla/usabilla-u4a-xamarin#17]
Hello,

First of all thank you for creating these bindings.
We've been using our own bindings so far and it was a nice surprise to see that you're now providing them yourselves.

Can you please document for each Xamarin.iOS / Xamarin.Android version what native version is wrapped. Ideally maybe as release notes for each Nuget package - https://www.nuget.org/packages/Usabilla.Xamarin

Regards,
Cosmin

**Comment by cosminstirbu** [comment]
Hello,

Any news on this?

Thanks,
Cosmin

**Comment by torkvell** [comment]
Hi @cosminstirbu ,

Thanks for reaching out on this. We've actually included this in our own release notes: https://github.com/usabilla/usabilla-u4a-xamarin/releases

I'll also make sure to communicate this to our SDK team so they can take this into consideration when releasing a Nuget package. 

If there is anything else, please let us know.
