### ISSUE TITLE
iOS: FormDidClose not called on the delegate

### ISSUE THREAD

**Issue by deyupopp** [usabilla/usabilla-u4a-xamarin#21]
After completing a form, if the user submits or cancels, no callbacks are called on the delegate.
The form is successfully dismissed, but FormDidClose is never called. Also, when you set DismissAutomatically to true, FormWillClose is never called.

**Comment by torkvell** [comment]
Hi @deyupopp ,

Thanks for reaching out to support on this and pardon for the late reply. 

The FormDidClose event is not part of the Xamarin bridge yet. We might get this implemented in future releases, but is not yet a decided part of the roadmap. 

If there is anything else we can help you with, please let us know.
