### ISSUE TITLE
iOS: Cannot use PreloadFeedbackForms

### ISSUE THREAD

**Issue by deyupopp** [usabilla/usabilla-u4a-xamarin#22]
Whenever trying to call PreloadFeedbackForms, application crashes with 
`NSInvalidArgumentException Reason: +[Usabilla preloadFeedbackForms:]: unrecognized selector sent to class 0x116b232e8`.

**Comment by torkvell** [comment]
Hi @deyupopp ,

Thanks for reaching out to support on this and pardon for the late reply.

The PreloadFeedbackForms function is not part of the Xamarin bridge yet. You can see all the current methods you can use from the [GitHub documentation](https://github.com/usabilla/usabilla-u4a-xamarin)

In the sample app we provide, we do have some methods and classes defined, but not all of them are implemented yet. 

I hope this clarifies. If there is anything else we can help you with, please let us know.
