### ISSUE TITLE
Android: Android Bindings are not available through NuGet

### ISSUE THREAD

**Issue by deyupopp** [usabilla/usabilla-u4a-xamarin#23]
When adding the Xamarin.Usabilla NuGet in an Xamarin Android project, the Bindings project is not available. 

Steps to reproduce:
1. Create a new Xamarin.Android project
2. Add the Xamarin.Usabilla NuGet and restore packages
3. Try to import the Android Bindings with `using UsabillaAndroid;`

The namespace cannot be found, so we cannot use the library. 

Note that in the sample app, the Bindings project is added as a reference, instead of a NuGet package. That is the dll that is needed in Android projects, so until that is published via NuGet, the sdk cannot be used in Xamarin Android projects, at least without using Xamarin.Forms.

**Comment by torkvell** [comment]
Hi @deyupopp ,

Thanks for your patience on this. We just created a Xamarin project with an Android-only project. We followed your steps and were able to access the namespace. Do note that the target SDK version will only work from 9.0.
![image](https://user-images.githubusercontent.com/40064170/60978431-6e412980-a331-11e9-9895-d0c50b5f8563.png)

**Comment by deyupopp** [comment]
Hi, @torkvell , thanks a lot for your reply. I'm not sure what went wrong when I first tried to use the NuGet package, but I can confirm that now I'm able to see it in our project. Will get back to you after I will replace everything in our application, as we previously used an in-house binding library, but this issue can definitely be closed. Thank you.
