### ISSUE TITLE
Not supported in. .net 2.0

### ISSUE THREAD

**Issue by singh-akhilesh-svg** [usabilla/usabilla-u4a-xamarin#54]
Package Usabilla.Xamarin 1.3.2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Usabilla.Xamarin 1.3.2 supports:
  - monoandroid90 (MonoAndroid,Version=v9.0)
  - monoandroid90xamarinios10 (monoandroid90+xamarinios10,Version=v0.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

**Comment by eduakaszas** [comment]
Hi @singh-akhilesh-svg,

Thank you for reporting this. 

We'll investigate this on our end and get back to you with more information as soon as possible. 

Kind regards, 
Édua

**Comment by singh-akhilesh-svg** [comment]
Hi @eduakaszas Is there any progress?
I need to implement it in my project and client need it asap.
Please let me know.

**Comment by eduakaszas** [comment]
Hi @singh-akhilesh-svg, 

Our developers are actively looking into this at the moment, we apologise for the delay. 

We'll get back to you shortly with an update. 

Kind regards, 
Édua

**Comment by singh-akhilesh-svg** [comment]
Hi @eduakaszas  
Is there any update on this issue.

**Comment by eduakaszas** [comment]
Hi @singh-akhilesh-svg , 

Thank you for your patience & apologies about the delay. 

We released a new update for the Xamarin bridge, which should solve the issue you're experiencing. 

Please try updating  to the latest version and feel free to reopen this ticket in case the issue still persists. 

Kind regards, 
Édua
