### ISSUE TITLE
No class def found error in .net 2.0 android 

### ISSUE THREAD

**Issue by singh-akhilesh-svg** [usabilla/usabilla-u4a-xamarin#59]
<img width="1095" alt="Screenshot 2021-05-04 at 3 41 22 PM" src="https://user-images.githubusercontent.com/63542850/116990169-5f8aea00-acf0-11eb-90b9-59a0abc55d8f.png">

**Comment by eduakaszas** [comment]
Hi @singh-akhilesh-svg, 

Thank you for reporting this. 

You'll need to make sure to add the Moshi package to your Xamarin Android app - that should fix the issue. Could you please try that and let us know how it goes?

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by singh-akhilesh-svg** [comment]
Thanks for your reply. Now from is submitted successfully but I got this issue when I click on dismiss button after submission.
<img width="878" alt="Screenshot 2021-05-04 at 9 44 36 PM" src="https://user-images.githubusercontent.com/63542850/117035598-1fdcf600-ad22-11eb-8060-65e292d3ebb1.png">
