### ISSUE TITLE
Regarding String Translation of Campaingn

### ISSUE THREAD

**Issue by akkhu** [usabilla/usabilla-u4a-xamarin#63]
Hi Usabilla,
I didn't found anything to translate SendEvent in Xamarin forms.

Please let me know asap.

Client is waiting for this.

**Comment by eduakaszas** [comment]
Hi @akkhu , 

Thank you for reaching out & we're sorry about the late response on this!

Could you please clarify what you mean exactly by `translate SendEvent` ? What would you like to translate?

Looking forward to hearing from you. 

Kind regards, 
Édua
