### ISSUE TITLE
Usabilla campaigns are not displayed when triggering an event

### ISSUE THREAD

**Issue by jdumasleon** [usabilla/usabilla-u4a-xamarin#66]
Hello, 

I am using your platform for topics related to surveys and feedback. I have integrated the latest version of the SDK in my Forms project and both platforms, but I have found that the campaigns do not work on the iOS platform for some unknown reason.

Android
- Passive Feedback -> works OK
- Active Feedback -> works OK

iOS
- Passive Feedback -> works OK
- Active Feedback -> *** KO *** 

For some reason that I have not been able to determine, the campaigns do not work when launching the event on iOS. Nothing output terminal of the app is shown. I have also tried with the test example in the repository and it does not work either.

Emulator -> IPhone 12 iOS 14.5

Usabilla v2.0.0,
Xamarin Forms 5.0.0

Could you take a look and reproduce the error?

Thanks, 
Jose Luis

**Comment by lennardtastic** [comment]
Closing this issue due to it being stagnant.
