### ISSUE TITLE
Issues with Xamarin iOS

### ISSUE THREAD

**Issue by jcslim89** [usabilla/usabilla-u4a-xamarin#73]
Dears, 
I am trying to publish the app on the appstore but I noticed that the swift libraries are no longer being copied to the package for iOS.
For reference, when I added the latest version of the Usabilla framework for iOS it automatically installs xamarin.Swift3 and xamarin.Swift4 ignoring the xamarin.Swift package already installed (which should support all versions of swift). And it seems I cannot build the project when all 3 swift projects are together. If I remove the xamarin.Swift it builds but archiving the project seems to no longer copy the Swift libraries to the package itself which is causing us to receive this message from Itunes:
ITMS-90424: Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
I would remove xamarin.Swift3 and Xamarin.swift4 if I could but usabilla is dependent on it. Please advise

**Comment by jcslim89** [comment]
Hello, 
Has anyone looked at this issue as we are in need to use the library but unable to publish due to this issue.

**Comment by andlie** [comment]
We have just now release 2 version of our SDK
Version 2.0.4 uses Swift 3 & 4
Version 2.05 uses Swift
Both version have the latest iOS SDK and Android SDK, enabling campaign reactivation
