### ISSUE TITLE
Campaign not displaying but ok for Forms

### ISSUE THREAD

**Issue by Denise-Ding** [usabilla/usabilla-u4a-xamarin#74]
Hi, I've tried unsuccessfully to display a Campaign in my Android Emulator.  Please help!!

I'm using Xamarin C# .NET solution with a Shared, Andriod and iOS projects. 
Shared project is using Target framework: Standard 2.0.
The Android project using Target framework Android version: Android 11.0 (R)

However, I have no problems displaying a Form with following code in the Android Emulator - UsabillaXamarin.Instance.ShowFeedbackForm(FormId, (XUFormCompletionResult) 
I've not even attempted iOS yet.

With the debug mode (UsabillaXamarin.Instance.DebugEnabled = true) turned on, I got some logging (showing below) that campaign was triggered but it doesn't display.  Is it hidden somehow?? 
The Campaign has: 
- Custom event, Show campaign when: showme  (I have also tried Standard event 'App launch' with no luck)
- Trigger when even has occurred 1 time(s).
- and 100% of visitors

[UBInfo] Event "showme" sent!
[UBInfo] GET https://sdk.out.usbla.net/campaigns?app_id=43bb143c-8796-4047-b989-e6d695654a38
[UBInfo] 0, https://sdk.out.usbla.net/campaigns?app_id=43bb143c-8796-4047-b989-e6d695654a38, null
[UBInfo] GET https://sdk.out.usbla.net/targeting-options?ids[]=6f441aac-d26a-40c2-8953-19654f425a86
[UBInfo] 0, https://sdk.out.usbla.net/targeting-options?ids[]=6f441aac-d26a-40c2-8953-19654f425a86, null
[UBInfo] Campaign 4d0ce98a-77e2-4df6-bcee-152531983328 has been triggered!
[UBInfo] GET https://sdk.out.usbla.net/forms/1cf932aa-ad06-4f05-91b0-ca33fe1d48f3
[UBInfo] 0, https://sdk.out.usbla.net/forms/1cf932aa-ad06-4f05-91b0-ca33fe1d48f3, null
[UBInfo] 0, https://sdk.out.usbla.net/forms/1cf932aa-ad06-4f05-91b0-ca33fe1d48f3, null

This is part of the code that activates the campaign.  The activation of Form is commented but works.

      private void ShowFeedback()
        {           
            try
            {
                string eventText = "showme";
                Action<IXUFormCompletionResult> handler = formCompletionHandler;                
                Application.Current.MainPage.Unfocus();
                bool isFocus = Application.Current.MainPage.IsFocused;

                UsabillaXamarin.Instance.SendEvent(eventText, handler);
                
                // Unable to activate campaign
                //UsabillaXamarin.Instance.SendEvent(eventText, (XUFormCompletionResult) =>
                //{
                //// XUFormCompletionResult contains the following information: 
                //// isFormSucceeded:  this tells whether a form is shown or not
                //// formId: this is an optional field which occurs when called via passive forms
                //// result contains an object :
                //// rating: this value contains the response to the Mood/Star rating question. 
                //// sent: this value contains whether Campaign / Form is sent.
                //// abandonedpageindex: this value is set if the user Campaign is closed before submission. 
                //// isRedirectToAppStoreEnabled: defining a value will enable the App Store Rating prompt.
                //// description :  this is an optional field which tells error description

                //bool formSucced = XUFormCompletionResult.isFormSucceeded;
                //    bool sent = XUFormCompletionResult.result == null ? false : XUFormCompletionResult.result.Sent;
                //    Logging.GetInstance().Log(Logging.Level.Debug, $"- HAPP - GetFeedback Campaign {formSucced} and {sent}");

                //});

            }
            catch (Exception ex)
            {
                Logging.GetInstance().Log(Logging.Level.Error, $"Usabilla GetFeedback Campaign error {ex}");
            }

            // 63b38f26aa6f8528da58c19b - Feedback form
            // 63b5178101746739692d7bf0 - Enquiry form
            // Form works !!
            //string FormId = "63b5178101746739692d7bf0";
            //if (!string.IsNullOrEmpty(FormId))
            //{
            //    UsabillaXamarin.Instance.ShowFeedbackForm(FormId, (XUFormCompletionResult) =>
            //    {
            //        // XUFormCompletionResult contains the following information: 
            //        // isFormSucceeded:  this tells whether a form is shown or not
            //        // formId: this is an optional field which occurs when called via passive forms
            //        // result contains an object :
            //        // rating: this value contains the response to the Mood/Star rating question. 
            //        // sent: this value contains whether Campaign / Form is sent.
            //        // abandonedpageindex: this value is set if the user Campaign is closed before submission. 
            //        // isRedirectToAppStoreEnabled: defining a value will enable the App Store Rating prompt.
            //        // description :  this is an optional field which tells error description

            //        bool formSucced = XUFormCompletionResult.isFormSucceeded;
            //        bool sent = XUFormCompletionResult.result == null ? false : XUFormCompletionResult.result.Sent;
            //        Logging.GetInstance().Log(Logging.Level.Debug, $"GetFeedback Form {formSucced} and {sent}");
            //    });
            //}
        }

        private void formCompletionHandler(IXUFormCompletionResult res)
        {
            Logging.GetInstance().Log(Logging.Level.Debug, $"GetFeedback Campaign form result: {res}");
        }

**Comment by Denise-Ding** [comment]
Hi, I just managed to work it out after a week of fiddle-around with the code.
2 issues:
- I need to initialize the AppId in all the projects: Shared, Android and iOS, which I previously didn't initialise in Shared project.
- I only realised the Campaign can only get kicked off ONCE after the app has been launched.  I can now have different Campaigns kicked off but not multiple times for the same Campaign.  The pain is while development I would want to activate the SentEvent() often, but it would not display subsequent attempts.  I had to shut-down Emulator and Visual Studio, and restart Abs Server in order to 'clear' the queue somehow, so the Campaign would show again.  I guess that's the whole point of avoiding survey fatigue in real situation.  **Is there any options to manually clear the Campaign queue**?
Thanks.

**Comment by andlie** [comment]
You can call the reset() method

UsabillaXamarin.Instance.Reset();

It will clear every cache and reload all campaigns. For development testing. Make sure its not in the app you shio, as campaigns will keep appearing, and any counting (eg only show campaign after 5th sendEvent("[event]"), will be remove by this method

**Comment by Denise-Ding** [comment]
Thanks very much @andlie
