### ISSUE TITLE
Unable to display Campaign in iOS

### ISSUE THREAD

**Issue by Denise-Ding** [usabilla/usabilla-u4a-xamarin#75]
Hi,
I'm having issue showing Campaign for Xamarin iOS on iPhone.  Please help!
I can show Campaign and Form for Xamarin Android Emulator fine.

I'm using Xamarin C# .NET solution with 3 projects (Shared, Android and iOS) on Windows Visual Studio 2022 IDE.
The **Shared** project using Target framework: Standard 2.0 with:
 - Usabilla.Xamarin package 2.0.2 (latest)
 - Xamarin.Shift3 package, version 3.3.0.1 (latest) - unsure if required
 - Xamarin.Shift4 package, version 4.0.0.2 (latest) - unsure if required
 
The **iOS** project using Xamarin.iOS version 15.8.0.5 with:
 - Xamarin.Shift3 package, version 3.3.0.1 (latest)
 - Xamarin.Shift4 package, version 4.0.0.2 (latest)
 - Usabilla.Xamarin package 2.0.2

I can't use Xamarin.Shift because I get error - 'The "ProduceIncludeFrameworksCommand" task was not given a value for the required parameter "XcodePath".' and unsure how to fix that.

I do not see any `'[UBInfo] xxx'` debugging Output for iOS, but I can see them during Android activation.

This is how I test the mobile app:
I linked up my test iPhone to Visual Studio 2022, and run the mobile app.  The mobile app runs fine on the iphone.
When the timer event kicked off on a page and run the 'UsabillaXamarin.Instance.SendEvent(eventText, handler)', nothing happens.
I only see my own logging text ` 'GetFeedback showme Campaign activated.'` in the Visual Studio Output window.
Here's snippets of my code.

In **Shared** project, in App.xaml.cs, I initialise as such (AppId = 43bb143c-8796-4047-b989-e6d695654a38):
```
using Xamarin.Forms;
using Xamarin.Usabilla;

public partial class App
{
	// Other initializations
	
	InitialiseGetFeedback();
}

private void InitialiseGetFeedback()
{
	// external GetFeedback App ID
	UsabillaXamarin.Instance.DebugEnabled = true;
	string App_Id = "43bb143c-8796-4047-b989-e6d695654a38"; 
	UsabillaXamarin.Instance.Initialize(App_Id);

	if (Device.RuntimePlatform == Device.iOS)
	{
		UsabillaXamarin.Instance.LocalizedStringFile = "Localizable";
	}

	Logging.GetInstance().Log(Logging.Level.Info, "Initiliased GetFeedback.");
}

```
In a _separate_ class (Interface with System.ComponentModel.INoficationPropertyChanged) in the same Shared Xamarin project I activate the Campaign via a timer.
The Timer event activated after 5 seconds of the Page being viewed.
This is the same code called by Android Emulator and worked.

```
using Xamarin.Forms;
using Xamarin.Usabilla;
public class PageModel : INoficationPropertyChanged
{
    private System.Timers.Timer _timer;
	
    public override void ViewIsAppearing(object sender, EventArgs e)
    {
		_timer = new System.Timers.Timer();

		//Trigger event
		_timer.Interval = 5000; // after 5 seconds
		_timer.Elapsed += OnTimedEvent;
		_timer.Enabled = true;
    }
	
    private void OnTimedEvent(object sender, System.Timers.ElapsedEventArgs e)
    {	
		string eventText = "showme";
		Action<IXUFormCompletionResult> handler = formCompletionHandler;
		Application.Current.MainPage.Unfocus();

		try
		{
			UsabillaXamarin.Instance.SendEvent(eventText, handler);
			Logging.GetInstance().Log(Logging.Level.Debug, $"GetFeedback {eventText} Campaign activated.");
		}
		catch (Exception ex)
		{
			Logging.GetInstance().Log(Logging.Level.Error, $"Error activating GetFeedback Campaign {ex}");
		}

		_timer.Enabled = false;
    }

    private void formCompletionHandler(IXUFormCompletionResult res)
    {
		Logging.GetInstance().Log(Logging.Level.Debug, $"- HAPP - GetFeedback Campaign form result: {res}");
    }
}
```

In **iOS** project, I initialise as such (same AppId):
```

using UsabillaIos;
using Xamarin.Forms;

[Register("AppDelegate")]
public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
{
     public override bool FinishedLaunching(UIApplication uiapp, NSDictionary options)
     {
        InitialiseGetFeedback();
			 
	 //... other initializations
			 
	 return base.FinishedLaunching(uiapp, options);	
    }
		
    private void InitialiseGetFeedback()
    {
            string getFeedback_AppId = "43bb143c-8796-4047-b989-e6d695654a38";
            Usabilla.DebugEnabled = true;
            Usabilla.CanDisplayCampaigns = true;
            Usabilla.Initialize(getFeedback_AppId, null);
            
            Logging.GetInstance().Log(Logging.Level.Debug, $"Initialised GetFeedback iOS.");
    }
}
```

**Comment by Denise-Ding** [comment]
Still no resolution after trying on Mac as well.

Now, as soon as UsabillaXamarin.Instance.Initialize(App_Id) on _Shared_ project or UsabillaIos.Usabilla.Initialize(appId, null) on _iOS_ project is called, the app would stop with 'The app has been terminated.' output message. Nothing else.

I've also tried with timer on both projects so the Initilize() function is delayed.  The app loaded fine with all functions, but as soon as it runs Initialize(), the app stops.

My physical test iPhone 7+ with version 15.7.2 OS runs fine without the Initialize() functions.  Not sure if Usabilla.Xamarin is sensitive to the version of my test phone.  This is the only test iPhone I have access to.

**Comment by andlie** [comment]
You are initialising the SDK twice.  You should only call 

UsabillaXamarin.Instance.Initialize([YOUR APP ID]).

You can do this in the shared .cs file of you application. No need to do it specifically for iOS and Android


To present a survey(Campaign) use the SendEvent method

Action<IXUFormCompletionResult> handler = formCompletionHandler;
UsabillaXamarin.Instance.SendEvent(eventText, handler);

Do take a look in the GitHub, sample-app 
"https://github.com/usabilla/usabilla-u4a-xamarin/tree/master/UsabillaBindings/Xamarin.Usabilla.Sample" to get an working example

**Comment by Denise-Ding** [comment]
Thanks very much for your reply Anders.  
I will pick this up again once the project is back on the agenda.  It's been put on hold at the time being.
